export const SHOW_LOADING = 'SHOW_LOADING' // 显示加载效果的方法类型值
export const HIDE_LOADING = 'HIDE_LOADING' // 隐藏加载效果的方法类型值
export const USER_INFO = 'USER_INFO' // 用户信息
export const ANALYSIS_PARAMS = 'ANALYSIS_PARAMS' // 分析管理中分析子集配置参数
export const ANALYSIS_PARAMS_ID = 'ANALYSIS_PARAMS_ID' // 保存分析参数生成的编号
export const COPY_ANALYSIS_PARAMS_ID = 'COPY_ANALYSIS_PARAMS_ID' // 复制分析参数生成的编号
export const EVENT_STORE_DATA = 'EVENT_STORE_DATA'
export const MANAGER_TREE_NODE_ID = 'MANAGER_TREE_NODE_ID' // 分析管理树节点编号
export const TEMP_MANAGER_TREE_NODE_ID = 'TEMP_MANAGER_TREE_NODE_ID' // 分析管理树节点编号
export const MANAGER_HIDE_MENU = 'MANAGER_HIDE_MENU' // 分析管理二级菜单
export const MANAGER_DISABLED_MENU = 'MANAGER_DISABLED_MENU' // 分析管理二级菜单
export const HOT_WORDS_SEARCH_OBJ = 'HOT_WORDS_SEARCH_OBJ' // 热词搜索下拉框数据集合
export const IS_DISABLED_MENU = 'IS_DISABLED_MENU' // 是否禁用二级菜单
export const SUBMIT_NEWFILE_TAB_ACTIVE = 'SUBMIT_NEWFILE_TAB_ACTIVE'
export const ANALYSIS_RESULT_ALL_DATA = 'ANALYSIS_RESULT_ALL_DATA' // 提交分析返回的所有数据
export const MAIN_SUBLINE = 'MAIN_SUBLINE'
export const MENU_EDIT_STATUS = 'MENU_EDIT_STATUS'
export const ANAVT_HIDE_MENU = 'ANAVT_HIDE_MENU'
export const ANAVT_DISABLED_MENU = 'ANAVT_DISABLED_MENU'
export const PARAM_TWO_STATUS = 'PARAM_TWO_STATUS'
export const MODEL_PAGE_TYPE = 'MODEL_PAGE_TYPE'
export const IS_HAS_PERMISSION = 'IS_HAS_PERMISSION' // 是否有航司权限
export const ANALYSIS_TYPE = 'ANALYSIS_TYPE' // 是否有航司权限
